apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: avikjis27/nodejs-webapp
        name: nodejs-webapp
        env:
        - name: BG_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BG_COLOR
        - name: FG_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FG_COLOR
    