apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp-svc
  name: nodeapp-svc
spec:
  ports:
  - name: 8080-3000
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp
  type: ClusterIP