# Default values for nodeapp-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
env:
  FG_COLOR: purple
  BG_COLOR: yellow

image:
  repository: avikjis27/nodejs-webapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 3000
