on:
  push:
    branches:
      - "*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build nodejs-webapp
        run: | 
          cd nodejs-webapp
          docker build . -t nodejs-webapp
          docker tag nodejs-webapp avikjis27/nodejs-webapp:latest
          docker push avikjis27/nodejs-webapp:latest
          